name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable

    steps:
      - uses: actions/checkout@v4

      - name: Init west
        run: |
          west init -l config
          west update
          west zephyr-export

      # IZQUIERDA (central + USB + pantalla)
      - name: Build LEFT
        run: |
          west build -s zmk/app -b nice_nano -- \
            -DSHIELD=splitkb_aurora_sofle_left \
            -DSNIPPET=studio-rpc-usb-uart \
            -DCONFIG_ZMK_STUDIO=y \
            -DCONFIG_ZMK_STUDIO_LOCKING=n

      - name: Copy left
        run: cp build/zephyr/zmk.uf2 left.uf2

      # DERECHA
      - name: Build RIGHT
        run: |
          west build -s zmk/app -b nice_nano -- \
            -DSHIELD=splitkb_aurora_sofle_right

      - name: Copy right
        run: cp build/zephyr/zmk.uf2 right.uf2

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: |
            left.uf2
            right.uf2
