# ================= OLED =================
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Driver SSD1306
CONFIG_SSD1306=y
CONFIG_SSD1306_DEFAULT=y

# Split (pantalla solo en central)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_DISPLAY_SPLIT=y
# ========== ENCODERS ==========
CONFIG_ZMK_KSCAN_GPIO=y
CONFIG_ZMK_BEHAVIOR_SENSOR_ROTATE=y
CONFIG_ZMK_ENCODER=y
