name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable

    steps:
      - uses: actions/checkout@v4

      - name: Init west
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build LEFT (Studio enabled)
        run: |
          west build -s zmk/app -b nice_nano -- \
            -DSHIELD=sofle_left \
            -DSNIPPET=studio-rpc-usb-uart \
            -DCONFIG_ZMK_STUDIO=y \
            -DCONFIG_ZMK_STUDIO_LOCKING=n

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: build/zephyr/zmk.uf2
