name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Initialize west
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Build left
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=sofle_left

      - name: Build right
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=sofle_right

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: |
            build/zephyr/zmk.uf2
